const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const zip=require('../ui/zip-native.min.js');
const ctx={TextEncoder,TextDecoder,Uint8Array,DataView,Set,Map,console,zip,Blob,TransformStream,ReadableStream,WritableStream,DOMException};vm.createContext(ctx);
for(const f of ['fflate.js','ymt-schema.js','engine.js','large-io.js'])vm.runInContext(fs.readFileSync('ui/'+f,'utf8'),ctx);
const E=ctx.AssetEngine,L=ctx.LargeIO;
const make=(name,blob)=>({name,path:name,size:blob.size,blob,parsed:E.parseName(name),category:E.classify(name)});
(async()=>{
 assert.equal(L.MAX,25*1024**3);assert.equal(L.MAX_FILES,50000);
 const header=new Uint8Array(16);header.set([82,83,67,55]);
 const files=[make('hair_000_u.ydd',new Blob([header])),make('hair_diff_000_a_uni.ytd',new Blob([header,new Uint8Array(2*1024**2)])),make('hair_diff_000_b_uni.ytd',new Blob([header]))];
 const config={name:'stream_test',mode:'addon',gender:'mp_m_freemode_01'},plan=E.plan(files,config);
 assert.equal(plan.issues.filter(i=>i.severity==='error').length,0);
 assert.ok(plan.files.every(f=>!f.bytes));assert.equal(new Set(plan.files.map(f=>f.path.slice(0,f.path.lastIndexOf('/')))).size,1);
 const chunks=[];let closed=false,largest=0;
 await L.writeResource(plan,new WritableStream({write:chunk=>{chunks.push(chunk);largest=Math.max(largest,chunk.length);},close:()=>{closed=true;}}));
 assert.equal(closed,true);assert.ok(largest<=512*1024,`largest chunk ${largest}`);
 const out=new Blob(chunks),b=new Uint8Array(await out.arrayBuffer());
 assert.ok(Buffer.from(b).includes(Buffer.from([0x50,0x4b,0x06,0x06])),'ZIP64 end directory missing');
 const archive=await L.openArchive(out,L.MAX,0);const item=archive.entries.find(e=>e.path.endsWith('hair_diff_000_a_uni.ytd'));
 assert.ok(item);assert.equal(item.size,files[1].size);
 const report=archive.entries.find(e=>e.path.endsWith('ditasha-report.json'));assert.equal(JSON.parse(new TextDecoder().decode(await L.smallBytes(report))).files.find(f=>f.source==='hair_diff_000_a_uni.ytd').size,files[1].size);
 const generated=archive.entries.find(e=>e.path.endsWith('fxmanifest.lua'));
 assert.ok(new TextDecoder().decode(await L.smallBytes(generated)).includes('SHOP_PED_APPAREL_META_FILE'));
 const imported=make('hair_diff_000_a_uni.ytd',new Blob());Object.assign(imported,{size:item.size,blob:undefined,entry:item.entry});
 const streaming=L.sourceStream(imported,undefined,true);let read=0;await streaming.readable.pipeTo(new WritableStream({write:chunk=>{read+=chunk.length;}}));await streaming.done;assert.equal(read,item.size);
 await assert.rejects(()=>L.openArchive(out,100,0),/25 GB/);
 await archive.reader.close();
 const pedFiles=['custom.ydd','custom.yft','custom.ytd','custom.ymt'].map(name=>make(name,new Blob([header])));const pedMeta=make('peds.meta',new Blob(['<CPedModelInfo__InitDataList/>']));pedMeta.metaRoot='CPedModelInfo__InitDataList';const pedPlan=E.plan([...pedFiles,pedMeta],{...config,mode:'preserve'});assert.ok(pedPlan.files.filter(f=>f.source.name.startsWith('custom.')).every(f=>f.path.startsWith('stream/peds/custom/')));
 const huge=make('hair_000_u.ydd',new Blob([header]));huge.size=25*1024**3;
 assert.equal(E.fileSize(huge),L.MAX);assert.ok(E.plan([huge],{...config,mode:'preserve'}).files[0].source.blob);
 const bad=make('hair_000_u.ydd',new Blob([new Uint8Array(20)])),badStream=L.sourceStream(bad,undefined,true);
 await assert.rejects(()=>badStream.readable.pipeTo(new WritableStream({write(){}})),/RSC7/);await badStream.done.catch(()=>{});
 const ctrl=new AbortController();ctrl.abort();await assert.rejects(()=>L.writeResource(plan,new WritableStream({write(){}}),{signal:ctrl.signal}),/Dibatalkan/);
 console.log('PASS: lazy File sources, item folders, bounded ZIP64 output and close, ZIP64 import/deferred decompression, cap rejection, 25 GiB metadata without allocation, invalid header and cancellation. No end-to-end 25 GiB disk run performed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
