from __future__ import annotations

from pathlib import Path

HEADER = """fx_version 'cerulean'
game 'gta5'

author 'Ditasha Editor'
description 'Automatically generated by Ditasha FiveM Sorting'
version '1.0.0'

"""


def _lua_path(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix().replace("'", "\\'")


def generate_manifest(resource_dir: str | Path) -> Path:
    root = Path(resource_dir)
    root.mkdir(parents=True, exist_ok=True)

    ymt_files = sorted(root.rglob('*.ymt'))
    lines = [HEADER.rstrip(), '']

    if ymt_files:
        lines.append('files {')
        for p in ymt_files:
            lines.append(f"    '{_lua_path(p, root)}',")
        lines.append('}')
        lines.append('')

        apparel = [p for p in ymt_files if 'freemode' in p.name.lower() or p.name.lower().startswith(('mp_m_', 'mp_f_'))]
        for p in apparel:
            lines.append(f"data_file 'SHOP_PED_APPAREL_META_FILE' '{_lua_path(p, root)}'")
        if apparel:
            lines.append('')

    lines.append("-- .ydd/.ytd streaming files inside stream/ are loaded automatically by FiveM.")
    manifest = root / 'fxmanifest.lua'
    manifest.write_text('\n'.join(lines).rstrip() + '\n', encoding='utf-8')
    return manifest


def generate_all_manifests(output_root: str | Path) -> list[Path]:
    root = Path(output_root)
    manifests = []
    for resource in ('[ditasha_peds]', '[ditasha_hair]', '[ditasha_clothes]', '[ditasha_misc]'):
        resource_dir = root / resource
        if resource_dir.exists():
            manifests.append(generate_manifest(resource_dir))
    return manifests
