import {inspect,optimize} from './texture-optimizer.js';
let files=[];
const $=s=>document.querySelector(s);
const fmt=n=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:n<1073741824?`${(n/1048576).toFixed(1)} MB`:`${(n/1073741824).toFixed(2)} GB`;
async function readFile(file){const MAX=512*1024**2;if(AssetEngine.fileSize(file)>MAX)throw Error('Optimizer maksimal 512 MB per file.');const controller=new AbortController(),stream=LargeIO.sourceStream(file,controller.signal,false),chunks=[];let total=0;await stream.readable.pipeTo(new WritableStream({write:chunk=>{total+=chunk.length;if(total>MAX)throw Error('File melewati batas optimizer 512 MB.');chunks.push(chunk);}}));await stream.done;const out=new Uint8Array(total);let o=0;for(const c of chunks){out.set(c,o);o+=c.length;}return out;}
function remember(file){if(file._optimizerOriginal)return;file._optimizerOriginal={blob:file.blob,entry:file.entry,size:file.size,invalidHeader:file.invalidHeader,headerDeferred:file.headerDeferred,optimized:file.optimized};}
function apply(file,result,preset){remember(file);file.blob=new Blob([result.bytes],{type:'application/octet-stream'});file.entry=null;file.size=result.bytes.length;file.invalidHeader=false;file.headerDeferred=false;file.optimized={preset,changed:result.changed,beforeBytes:result.beforeBytes,afterBytes:result.afterBytes,at:Date.now()};}
function restore(file){const old=file?._optimizerOriginal;if(!old)return false;file.blob=old.blob;file.entry=old.entry;file.size=old.size;file.invalidHeader=old.invalidHeader;file.headerDeferred=old.headerDeferred;file.optimized=old.optimized;delete file._optimizerOriginal;return true;}
function refreshWorkspace(){const q=$('#search');if(q)q.dispatchEvent(new Event('input',{bubbles:true}));}
function activeFiles(){const modelId=$('#model-choice')?.value,ytdId=$('#ytd-choice')?.value;return{ydd:files.find(f=>String(f.id)===String(modelId)&&f.parsed.ext==='ydd'),ytd:ytdId&&ytdId!=='embedded'?files.find(f=>String(f.id)===String(ytdId)&&f.parsed.ext==='ytd'):null};}
function maxDimension(){const preset=$('#optimizer-preset')?.value||'safe';if(preset==='safe')return 2048;if(preset==='balanced')return 1024;if(preset==='aggressive')return 512;return +($('#optimizer-custom')?.value||2048);}
function updateAvailability(){const{ydd,ytd}=activeFiles(),ytdCheck=$('#optimizer-ytd'),yddCheck=$('#optimizer-ydd'),undo=$('#optimizer-undo');if(ytdCheck){ytdCheck.disabled=!ytd;if(!ytd)ytdCheck.checked=false;}if(yddCheck)yddCheck.disabled=!ydd;if(undo)undo.disabled=!((ydd&&ydd._optimizerOriginal)||(ytd&&ytd._optimizerOriginal));const custom=$('#optimizer-custom');if(custom)custom.hidden=$('#optimizer-preset')?.value!=='custom';}
async function summarize(file){const data=await readFile(file),kind=file.parsed.ext,list=inspect(data,kind),large=list.filter(t=>t.supported&&Math.max(t.width,t.height)>maxDimension());return{data,kind,list,large};}
async function run(){const btn=$('#optimizer-run'),note=$('#optimizer-result');if(btn.disabled)return;const{ydd,ytd}=activeFiles(),targets=[];if($('#optimizer-ytd').checked&&ytd)targets.push(ytd);if($('#optimizer-ydd').checked&&ydd)targets.push(ydd);if(!targets.length){note.textContent='Pilih YTD atau embedded YDD yang ingin dioptimalkan.';return;}btn.disabled=true;note.classList.remove('error');note.textContent='Menganalisis tekstur…';const limit=maxDimension(),preset=$('#optimizer-preset').value;try{let totalBefore=0,totalAfter=0,changed=0,details=[];for(const file of targets){note.textContent=`Mengoptimalkan ${file.name}…`;const data=await readFile(file),result=optimize(data,file.parsed.ext,{maxDimension:limit,minDimension:32});if(result.changed){apply(file,result,preset);totalBefore+=result.beforeBytes;totalAfter+=result.afterBytes;changed+=result.changed;details.push(`${file.name}: ${result.changed} tekstur`);}else details.push(`${file.name}: tidak ada tekstur > ${limit}px`);}refreshWorkspace();updateAvailability();note.textContent=changed?`${details.join(' · ')} · ${fmt(totalBefore)} → ${fmt(totalAfter)} (${Math.max(0,Math.round((1-totalAfter/totalBefore)*100))}% lebih kecil). Tutup/buka tab untuk memuat ulang preview.`:details.join(' · ');}catch(error){note.classList.add('error');note.textContent='Optimizer gagal: '+(error.message||error);}finally{btn.disabled=false;}}
function undo(){const{ydd,ytd}=activeFiles();let count=0;if(ydd&&restore(ydd))count++;if(ytd&&restore(ytd))count++;refreshWorkspace();updateAvailability();$('#optimizer-result').classList.remove('error');$('#optimizer-result').textContent=count?`${count} file dikembalikan ke versi sebelum optimasi. Tutup/buka tab untuk refresh.`:'Tidak ada optimasi yang bisa dibatalkan.';}
function install(){const options=$('.model-dock .model-options')||$('.model-options');if(!options||$('#texture-optimizer-panel'))return;const panel=document.createElement('div');panel.id='texture-optimizer-panel';panel.innerHTML=`<div class="model-divider"></div><div class="optimizer-title"><strong>Texture reducer</strong><span>OPTIMIZE</span></div><label for="optimizer-preset">Preset optimasi</label><select id="optimizer-preset"><option value="safe">Safe · maks. 2048px</option><option value="balanced">Balanced · maks. 1024px</option><option value="aggressive">Aggressive · maks. 512px</option><option value="custom">Custom</option></select><select id="optimizer-custom" hidden><option value="4096">4096 px</option><option value="2048" selected>2048 px</option><option value="1024">1024 px</option><option value="512">512 px</option><option value="256">256 px</option></select><label class="model-checkbox"><input type="checkbox" id="optimizer-ytd" checked> Optimalkan YTD yang dipilih</label><label class="model-checkbox"><input type="checkbox" id="optimizer-ydd"> Optimalkan tekstur embedded di YDD aktif</label><p class="field-note">Safe direkomendasikan. Resolusi besar diperkecil dan mipmap dibuat ulang dengan format tekstur yang sama. Geometry YDD tidak diubah.</p><div class="optimizer-actions"><button class="secondary" id="optimizer-run">Optimize textures</button><button class="text-button" id="optimizer-undo" disabled>Undo</button></div><p id="optimizer-result" class="optimizer-result">Pilih YTD lalu jalankan optimizer.</p>`;options.append(panel);const style=document.createElement('style');style.id='texture-optimizer-style';style.textContent=`#texture-optimizer-panel{margin-top:4px}.optimizer-title{display:flex;align-items:center;justify-content:space-between;margin:10px 0}.optimizer-title strong{font-size:12px}.optimizer-title span{font-size:8px;letter-spacing:1px;color:var(--lime);border:1px solid #d9f76b33;padding:2px 5px;border-radius:3px}.optimizer-actions{display:flex;gap:12px;align-items:center;margin-top:10px}#optimizer-run{flex:1}.optimizer-result{font-size:9px;line-height:1.55;color:#8f98a6;margin:9px 0 0;overflow-wrap:anywhere}.optimizer-result.error{color:#f4a49c}`;document.head.append(style);$('#optimizer-preset').onchange=updateAvailability;$('#optimizer-run').onclick=run;$('#optimizer-undo').onclick=undo;$('#ytd-choice').addEventListener('change',()=>setTimeout(updateAvailability,0));$('#model-choice').addEventListener('change',()=>setTimeout(updateAvailability,0));updateAvailability();}
export function attach(currentFiles){files=currentFiles;install();updateAvailability();}
