import * as THREE from './vendor/three.module.js';
import {OrbitControls} from './vendor/OrbitControls.js';
import {MAX_MODELS,MAX_DECODED,MAX_TEXTURES,withinModelBudget,rowOffsets} from './preview-state.js';
const $=s=>document.querySelector(s),P=globalThis.GtaPreview;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let files=[],units=new Map(),active=null,renderer=null,scene,camera,controls,group,grid,observer,frame,generation=0,loading=false,dockReady=false;
const staging=new Set();
const selected=new Set();
function status(message,error=false){$('#model-status').textContent=message;$('#model-status').classList.toggle('error',error);}
function request(unit,action,data={}){
 if(!unit.worker){unit.worker=new Worker('./preview-worker.js');unit.worker.onmessage=e=>{const task=unit.pending.get(e.data.id);if(!task)return;unit.pending.delete(e.data.id);e.data.error?task.reject(Error(e.data.error)):task.resolve(e.data.result);};unit.worker.onerror=()=>{for(const task of unit.pending.values())task.reject(Error('Pemroses preview gagal.'));unit.pending.clear();};}
 const id=++unit.nextId;return new Promise((resolve,reject)=>{unit.pending.set(id,{resolve,reject});try{unit.worker.postMessage({id,action,...data},data.bytes?[data.bytes.buffer]:[]);}catch(error){unit.pending.delete(id);reject(error);}});
}
async function readFile(file,signal){
 const MAX=128*1024**2;if(AssetEngine.fileSize(file)>MAX)throw Error('File preview maksimal 128 MB.');
 LargeIO.checkAbort(signal);const stream=LargeIO.sourceStream(file,signal,false),chunks=[];let total=0;
 try{await stream.readable.pipeTo(new WritableStream({write:chunk=>{total+=chunk.length;if(total>MAX)throw Error('File preview melewati 128 MB.');chunks.push(chunk);}}),{signal});await stream.done;const data=new Uint8Array(total);let offset=0;for(const chunk of chunks){data.set(chunk,offset);offset+=chunk.length;}return data;}catch(error){await stream.done.catch(()=>{});throw error;}
}
function clearMeshes(unit){for(const mesh of [...unit.root.children]){mesh.geometry.dispose();mesh.material.dispose();unit.root.remove(mesh);}}
function clearTextures(unit){for(const texture of unit.cache.values())texture.dispose();unit.cache.clear();unit.textureBytes=0;}
function destroyUnit(unit){unit.controller.abort();unit.textureController?.abort();unit.worker?.terminate();for(const task of unit.pending.values())task.reject(Error('Model ditutup.'));unit.pending.clear();clearMeshes(unit);clearTextures(unit);group?.remove(unit.root);}
function initScene(){if(renderer)return;renderer=new THREE.WebGLRenderer({canvas:$('#model-canvas'),antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setClearColor(0x12151b);scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(40,1,.001,10000);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;scene.add(new THREE.HemisphereLight(0xffffff,0x62748a,2));for(const[position,color,power]of[[[3,5,4],0xffffff,3],[[-4,2,-3],0xc6d6ff,1.5]]){const light=new THREE.DirectionalLight(color,power);light.position.set(...position);scene.add(light);}group=new THREE.Group();group.rotation.x=-Math.PI/2;scene.add(group);observer=new ResizeObserver(resize);observer.observe($('#model-stage'));resize();const animate=()=>{frame=requestAnimationFrame(animate);controls.update();renderer.render(scene,camera);};animate();}
function resize(){if(!renderer)return;const stage=$('#model-stage'),w=stage.clientWidth,h=stage.clientHeight;if(!w||!h)return;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}
function fitCamera(){if(!group?.children.length)return;group.updateMatrixWorld(true);const visible=[...units.values()].filter(u=>u.root.visible!==false);if(!visible.length)return;const box=new THREE.Box3();for(const unit of visible)box.expandByObject(unit.root);if(box.isEmpty())return;const size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),radius=Math.max(size.x,size.y,size.z,.01);camera.position.copy(center).add(new THREE.Vector3(radius*1.25,radius*.8,radius*1.6));camera.near=radius/1000;camera.far=radius*100;camera.updateProjectionMatrix();controls.target.copy(center);controls.minDistance=radius*.05;controls.maxDistance=radius*20;controls.update();if(grid){scene.remove(grid);grid.geometry.dispose();grid.material.dispose();}grid=new THREE.GridHelper(radius*2.5,20,0x46503b,0x252d38);grid.position.set(center.x,box.min.y-radius*.02,center.z);scene.add(grid);}
function arrange(){const all=[...units.values()];for(const unit of all)unit.root.position.set(0,0,0);if($('#model-layout-choice').value==='row'){for(const unit of all)unit.root.visible=true;group.updateMatrixWorld(true);const boxes=all.map(unit=>new THREE.Box3().setFromObject(unit.root)),widths=boxes.map(box=>box.getSize(new THREE.Vector3()).x);rowOffsets(widths).forEach((offset,i)=>{all[i].root.position.x=offset-boxes[i].getCenter(new THREE.Vector3()).x;});}else if(active){for(const unit of all)unit.root.visible=unit===active;}fitCamera();}
function drawables(unit){return unit.drawable==='all'?unit.model.drawables:[unit.model.drawables[+unit.drawable]].filter(Boolean);}
function statistics(){let vertices=0,triangles=0,drawableCount=0;for(const unit of units.values()){drawableCount+=drawables(unit).length;for(const mesh of unit.root.children){vertices+=mesh.geometry.getAttribute('position').count;triangles+=mesh.geometry.index.count/3;}}$('#model-stats').textContent=`${units.size} YDD · ${drawableCount} drawable · ${vertices.toLocaleString('id-ID')} vertex · ${triangles.toLocaleString('id-ID')} segitiga`;}
function buildMeshes(unit){clearMeshes(unit);for(const drawable of drawables(unit)){const level=drawable.lods.find(l=>l.name===unit.lod)||drawable.lods[0];for(const m of level.meshes){const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(m.positions,3));if(m.uvs)geometry.setAttribute('uv',new THREE.BufferAttribute(m.uvs,2));geometry.setIndex(new THREE.BufferAttribute(m.indices,1));geometry.computeVertexNormals();const material=new THREE.MeshStandardMaterial({color:0xbec9d4,roughness:.85,metalness:0,side:THREE.DoubleSide,wireframe:$('#wireframe-toggle').checked});const mesh=new THREE.Mesh(geometry,material);mesh.userData={diffuse:m.material.diffuse,embedded:drawable.embedded,hasUV:!!m.uvs};unit.root.add(mesh);}}applyMaps(unit);statistics();arrange();}
function embedded(unit){return drawables(unit).flatMap(drawable=>drawable.embedded);}
function lookup(unit,mesh){return unit.texture!=='auto'?unit.metadata.find(t=>t.name===unit.texture)||embedded(unit).find(t=>t.name===unit.texture):P.matchTexture(mesh.userData.diffuse,unit.metadata)||P.matchTexture(mesh.userData.diffuse,mesh.userData.embedded);}
function applyMaps(unit){for(const mesh of unit.root.children){const candidate=lookup(unit,mesh),texture=candidate&&unit.cache.get(candidate.name);mesh.material.map=mesh.userData.hasUV?texture||null:null;mesh.material.color.set(texture?0xffffff:0xbec9d4);mesh.material.alphaTest=texture?0.2:0;mesh.material.needsUpdate=true;}}
function textureOptions(unit){const options=[...new Map([...unit.metadata,...embedded(unit)].map(t=>[t.name,t])).values()];$('#texture-choice').innerHTML='<option value="auto">Otomatis sesuai material</option>'+options.map(t=>`<option value="${esc(t.name)}">${esc(t.name)} · ${t.width}×${t.height}</option>`).join('');$('#texture-choice').value=unit.texture;$('#texture-choice').disabled=false;}
function populateYtd(unit){const matched=P.candidateFiles(unit.file,files),all=files.filter(f=>f.parsed.ext==='ytd'),choices=unit.showAll?all:matched.length?matched:all;$('#ytd-choice').innerHTML='<option value="embedded">Tanpa YTD / tekstur bawaan</option>'+choices.map(f=>`<option value="${f.id}">${esc(f.name)}</option>`).join('');if(!unit.ytd)unit.ytd=matched.length?String(matched[0].id):'embedded';if(unit.ytd!=='embedded'&&!choices.some(f=>String(f.id)===unit.ytd))unit.ytd='embedded';$('#ytd-choice').value=unit.ytd;$('#ytd-match-note').textContent=matched.length?`${matched.length} YTD pasangan ditemukan.`:all.length?'Pilih YTD secara manual.':'Belum ada YTD diimpor.';}
function activate(unit){active=unit;$('#model-choice').value=String(unit.file.id);$('#drawable-choice').innerHTML='<option value="all">Semua drawable</option>'+unit.model.drawables.map((d,i)=>`<option value="${i}">${esc(d.name)}</option>`).join('');$('#drawable-choice').value=unit.drawable;$('#lod-choice').innerHTML=[...new Set(unit.model.drawables.flatMap(d=>d.lods.map(l=>l.name)))].map(l=>`<option>${esc(l)}</option>`).join('');$('#lod-choice').value=unit.lod;$('#all-ytd-toggle').checked=unit.showAll;populateYtd(unit);textureOptions(unit);for(const id of ['drawable-choice','lod-choice','ytd-choice'])$('#'+id).disabled=unit.busy;$('#texture-choice').disabled=unit.busy;$('#all-ytd-toggle').disabled=unit.busy;renderTabs();arrange();}
async function decodeMaps(unit){const gen=generation,token=++unit.token,names=[...new Set(unit.root.children.map(mesh=>lookup(unit,mesh)?.name).filter(Boolean))];if(!names.length){applyMaps(unit);if(active===unit)status('Belum ada tekstur cocok. Pilih YTD atau gambar tekstur.');return;}try{if(active===unit)status('Menyiapkan tekstur…');const decoded=await request(unit,'decode',{names});if(gen!==generation||token!==unit.token)return;const total=decoded.textures.reduce((sum,t)=>sum+t.data.byteLength,0),other=[...units.values()].filter(u=>u!==unit).reduce((sum,u)=>sum+u.textureBytes,0);if(other+total>MAX_TEXTURES)throw Error('Tekstur gabungan melebihi 128 MB. Kurangi model atau pilih tekstur lebih kecil.');clearTextures(unit);for(const image of decoded.textures){const texture=new THREE.DataTexture(image.data,image.width,image.height,THREE.RGBAFormat);texture.colorSpace=THREE.SRGBColorSpace;texture.flipY=false;texture.wrapS=texture.wrapT=THREE.RepeatWrapping;texture.anisotropy=Math.min(renderer.capabilities.getMaxAnisotropy(),8);texture.needsUpdate=true;unit.cache.set(image.name,texture);}unit.textureBytes=total;applyMaps(unit);if(active===unit){const mapped=unit.root.children.filter(m=>m.material.map).length;status(decoded.warnings.length?decoded.warnings.join(' · '):`${unit.file.name}: ${mapped} dari ${unit.root.children.length} mesh memakai tekstur.`,!!decoded.warnings.length);}}catch(error){if(gen===generation&&active===unit)status('Tekstur tidak dapat dipreview: '+error.message,true);}}
async function loadYtd(unit){const gen=generation,token=++unit.token,loadVersion=++unit.loadVersion;unit.textureController?.abort();unit.textureController=new AbortController();unit.busy=true;unit.metadata=[];unit.ytdBytes=0;unit.texture='auto';clearTextures(unit);applyMaps(unit);if(active===unit)activate(unit);try{let result;if(unit.ytd==='embedded')result=await request(unit,'embedded');else{const file=files.find(f=>String(f.id)===unit.ytd);if(!file)throw Error('YTD tidak ditemukan.');const bytes=await readFile(file,unit.textureController.signal);if(gen!==generation||token!==unit.token)return;result=await request(unit,'ytd',{bytes});}if(gen!==generation||token!==unit.token)return;const used=[...units.values()].reduce((sum,u)=>sum+(u.model.decodedBytes||0)+(u===unit?0:u.ytdBytes),0);if(used+(result.decodedBytes||0)>MAX_DECODED){await request(unit,'embedded');throw Error('Resource gabungan melebihi 512 MB. Kurangi model.');}unit.ytdBytes=result.decodedBytes||0;unit.metadata=result.textures;if(active===unit)textureOptions(unit);await decodeMaps(unit);}catch(error){if(gen===generation&&active===unit)status('YTD tidak dapat dipreview: '+error.message,true);}finally{if(gen===generation&&loadVersion===unit.loadVersion){unit.busy=false;if(active===unit)activate(unit);}}}
function listSelection(){const query=$('#model-filter').value.toLowerCase();$('#model-selection').innerHTML=files.filter(f=>f.parsed.ext==='ydd'&&f.name.toLowerCase().includes(query)).map(f=>`<label><input type="checkbox" data-select-model="${f.id}" ${selected.has(String(f.id))?'checked':''}>${esc(f.name)}</label>`).join('')||'<p>Tidak ada YDD cocok.</p>';}
async function loadModels(){if(loading)return;const wanted=[...selected];if(!wanted.length){status('Pilih minimal satu YDD.',true);return;}if(wanted.length>MAX_MODELS){status('Maksimal 4 YDD sekaligus.',true);return;}loading=true;const gen=generation;$('#load-models').disabled=true;const warnings=[];try{for(const[id,unit]of units)if(!selected.has(id)){destroyUnit(unit);units.delete(id);}for(const id of wanted){if(units.has(id))continue;const file=files.find(f=>String(f.id)===id),unit={file,root:new THREE.Group(),model:null,worker:null,pending:new Map(),nextId:0,cache:new Map(),metadata:[],textureBytes:0,ytdBytes:0,token:0,loadVersion:0,controller:new AbortController(),drawable:'all',lod:'High',ytd:null,texture:'auto',showAll:false,busy:false};staging.add(unit);try{status('Membaca '+file.name+'…');const bytes=await readFile(file,unit.controller.signal);if(gen!==generation){destroyUnit(unit);return;}unit.model=await request(unit,'model',{bytes});if(gen!==generation){destroyUnit(unit);return;}if(!withinModelBudget(units.values(),unit))throw Error('Gabungan preview melebihi 2 juta vertex atau 512 MB resource.');unit.lod=unit.model.drawables.flatMap(d=>d.lods)[0]?.name||'High';units.set(id,unit);staging.delete(unit);group.add(unit.root);buildMeshes(unit);activate(unit);await loadYtd(unit);}catch(error){staging.delete(unit);destroyUnit(unit);if(gen!==generation)return;units.delete(id);selected.delete(id);warnings.push(file.name+': '+error.message);}}
 if(gen!==generation)return;$('#model-choice').innerHTML=[...units.values()].map(unit=>`<option value="${unit.file.id}">${esc(unit.file.name)}</option>`).join('');if(!active||!units.has(String(active.file.id)))active=units.values().next().value||null;if(active)activate(active);else for(const id of ['model-choice','drawable-choice','lod-choice','ytd-choice','texture-choice'])$('#'+id).disabled=true;$('#model-choice').disabled=!active;listSelection();statistics();renderTabs();arrange();if(warnings.length)status(warnings.join(' · '),true);else status(`${units.size} YDD dibuka. Klik tab untuk berpindah model.`);
 }finally{if(gen===generation){loading=false;$('#load-models').disabled=false;}}}
function cleanup(){generation++;for(const unit of staging)destroyUnit(unit);staging.clear();for(const unit of units.values())destroyUnit(unit);units.clear();active=null;loading=false;cancelAnimationFrame(frame);observer?.disconnect();controls?.dispose();if(grid){grid.geometry.dispose();grid.material.dispose();}if(renderer){const canvas=renderer.domElement;renderer.dispose();renderer.forceContextLoss();canvas.replaceWith(canvas.cloneNode());}renderer=null;scene=null;group=null;grid=null;files=[];selected.clear();renderTabs();}
function injectDockStyles(){if($('#model-dock-style'))return;const style=document.createElement('style');style.id='model-dock-style';style.textContent=`
.work-grid>.right-rail{min-width:0;display:flex;flex-direction:column;gap:24px}.model-dock{border:1px solid var(--line);border-radius:8px;background:#181a1f;overflow:hidden;min-width:0}.model-dock[hidden]{display:none!important}.model-dock .dialog-heading{padding:15px 16px}.model-dock .dialog-heading h2{font-size:14px}.model-dock .model-subtitle{font-size:10px;margin-top:2px}.model-dock .model-layout{display:block}.model-dock .model-stage{height:300px;min-height:300px;border:0;border-radius:0}.model-dock .model-stage-label{font-size:8px;left:10px;top:9px}.model-dock .model-stage-bottom{padding:8px 10px;font-size:9px}.model-dock .model-stage-bottom span{display:none}.model-dock .model-options{border:0;border-top:1px solid var(--line);padding:14px 16px;max-height:390px;overflow:auto}.model-dock .model-options label{font-size:11px;margin-top:9px}.model-dock .model-options input,.model-dock .model-options select{font-size:11px;padding:7px 8px}.model-dock label[for="model-filter"],.model-dock #model-filter,.model-dock #model-selection,.model-dock #load-models,.model-dock label[for="model-choice"],.model-dock #model-choice{display:none!important}.model-dock .model-caveat{font-size:9px;line-height:1.5}.model-dock .model-footer{padding:10px 14px;display:block}.model-dock #model-stats{display:block;font-size:9px;margin-bottom:4px}.model-dock #model-status{font-size:10px}.model-tabs{display:flex;gap:4px;overflow-x:auto;padding:8px 10px;border-bottom:1px solid var(--line);background:#15171c;scrollbar-width:thin}.model-tab{flex:0 0 auto;max-width:170px;border:1px solid #343842;background:#1d2026;color:#9fa6b3;border-radius:5px;padding:6px 7px 6px 9px;font-size:10px;display:flex;gap:6px;align-items:center}.model-tab.active{color:var(--lime);border-color:#617039;background:#d9f76b0b}.model-tab-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.model-tab-close{border:0;background:transparent;color:#747b87;padding:0;font-size:14px;line-height:1}.model-tab-close:hover{color:#fff}.builder{order:2}@media(max-width:1050px){.work-grid{grid-template-columns:1fr!important}.work-grid>.right-rail{display:grid;grid-template-columns:1fr 1fr;align-items:start}.model-dock .model-stage{height:340px}}@media(max-width:760px){.work-grid>.right-rail{display:flex}.model-dock .model-stage{height:300px}}
`;document.head.append(style);}
function ensureDock(){if(dockReady)return $('#model-dock');injectDockStyles();const dialog=$('#model-dialog'),grid=$('.work-grid'),builder=$('.builder');if(!dialog||!grid||!builder)return null;let rail=$('.right-rail');if(!rail){rail=document.createElement('div');rail.className='right-rail';grid.insertBefore(rail,builder);rail.append(builder);}const dock=document.createElement('section');dock.id='model-dock';dock.className='model-dock';dock.hidden=true;while(dialog.firstChild)dock.append(dialog.firstChild);rail.insertBefore(dock,builder);const heading=dock.querySelector('.dialog-heading'),tabs=document.createElement('div');tabs.id='model-tabs';tabs.className='model-tabs';heading.after(tabs);const close=heading.querySelector('[data-close]');if(close)close.onclick=()=>{dock.hidden=true;};tabs.onclick=e=>{const closeBtn=e.target.closest('[data-close-tab]');if(closeBtn){e.stopPropagation();closeModelTab(closeBtn.dataset.closeTab);return;}const tab=e.target.closest('[data-model-tab]');if(tab){const unit=units.get(tab.dataset.modelTab);if(unit)activate(unit);}};dockReady=true;return dock;}
function renderTabs(){const tabs=$('#model-tabs');if(!tabs)return;tabs.innerHTML=[...units.entries()].map(([id,unit])=>`<button class="model-tab ${unit===active?'active':''}" data-model-tab="${id}" title="${esc(unit.file.name)}"><span class="model-tab-name">${esc(unit.file.name)}</span><span class="model-tab-close" data-close-tab="${id}" aria-label="Tutup tab">×</span></button>`).join('');}
function closeModelTab(id){const unit=units.get(String(id));if(!unit)return;const wasActive=unit===active;destroyUnit(unit);units.delete(String(id));selected.delete(String(id));if(wasActive)active=units.values().next().value||null;$('#model-choice').innerHTML=[...units.values()].map(u=>`<option value="${u.file.id}">${esc(u.file.name)}</option>`).join('');if(active)activate(active);else{$('#model-dock').hidden=true;statistics();}renderTabs();arrange();}
$('#model-dialog').addEventListener('close',cleanup);$('#model-filter').oninput=listSelection;$('#model-selection').onchange=event=>{const id=event.target.dataset.selectModel;if(!id)return;if(loading){event.target.checked=selected.has(id);return;}if(event.target.checked){if(selected.size>=MAX_MODELS){event.target.checked=false;status('Maksimal 4 YDD sekaligus.',true);return;}selected.add(id);}else selected.delete(id);};$('#load-models').onclick=loadModels;$('#model-layout-choice').onchange=arrange;$('#model-choice').onchange=()=>{const unit=units.get($('#model-choice').value);if(unit)activate(unit);};$('#ytd-choice').onchange=()=>{if(active){active.ytd=$('#ytd-choice').value;loadYtd(active);}};$('#all-ytd-toggle').onchange=()=>{if(active){active.showAll=$('#all-ytd-toggle').checked;populateYtd(active);loadYtd(active);}};$('#texture-choice').onchange=()=>{if(active){active.texture=$('#texture-choice').value;decodeMaps(active);}};$('#drawable-choice').onchange=()=>{if(active){active.drawable=$('#drawable-choice').value;buildMeshes(active);textureOptions(active);decodeMaps(active);}};$('#lod-choice').onchange=()=>{if(active){active.lod=$('#lod-choice').value;buildMeshes(active);decodeMaps(active);}};$('#wireframe-toggle').onchange=()=>{for(const unit of units.values())for(const mesh of unit.root.children)mesh.material.wireframe=$('#wireframe-toggle').checked;};$('#reset-camera').onclick=fitCamera;
export async function openPreview(currentFiles,modelId){const dock=ensureDock();if(!dock)throw Error('Panel preview tidak ditemukan.');files=currentFiles;import('./optimizer-ui.js').then(m=>m.attach(currentFiles)).catch(()=>{});const id=String(modelId??'');const valid=files.some(f=>String(f.id)===id&&f.parsed.ext==='ydd');if(valid&&!selected.has(id)){if(selected.size>=MAX_MODELS){status('Maksimal 4 tab YDD sekaligus. Tutup satu tab untuk membuka model lain.',true);dock.hidden=false;return;}selected.add(id);}else if(!selected.size){const first=files.find(f=>f.parsed.ext==='ydd');if(first)selected.add(String(first.id));}$('#model-filter').value='';$('#model-layout-choice').value='overlay';listSelection();dock.hidden=false;try{initScene();await loadModels();const unit=units.get(id)||active;if(unit)activate(unit);requestAnimationFrame(()=>{resize();fitCamera();});}catch(error){status('WebGL preview tidak tersedia: '+error.message,true);}}
